name: Webpack Demo

on: [push]

jobs:
  test:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Tests
        run: make ci DEMO=webpack
        env:
          CYPRESS_API_KEY: ${{ secrets.API_KEY }}
